# Build pipeline

resources:
  repositories:
    - repository: templates
      type: github
      name: unitycontainer/DevOps
      endpoint: Unity Container

trigger:
- master
- refs/tags/*

pool:
  vmImage: 'windows-latest'

steps:
- template: build-steps.yml@templates

